### ISSUE TITLE
[Tooling, low prio] Functionality to auto include module appointments into most calendar apps

### ISSUE THREAD

**Issue by Ironeer** [Compiler-CampusMinden/CB-Vorlesung-Master#106]
It would be a really cool feature to be able to download the module dates as a .ics file to import them into a calendar.

(if my time allows it I will try to propose an implementation)

**Comment by cagix** [comment]
i have been pondering that too :) ... however, i have added many individual appointments to my calendar, because the times and the lead often change. this would then also result in one .ics per appointment, which would no longer be a good choice ... another idea would be to create and share a google calendar - then you would have a url that you can subscribe to in your own calendar. but i have no experience with that so far. what do you think - shall we explore this second option?

**Comment by Ironeer** [comment]
Right, I forgot that .ics only supports one date or recurrent appointments. A synchronized Google calendar would be great. Most other apps (outlook etc.) should be able to subscribe to that too, shouldn't they? Does the list view visible on the website remain as a requirement? Then it would be nice to generate the list from the calendar or vice versa to have a single source of truth.

**Comment by cagix** [comment]
(a) Google calendar: In the preferences pane, different variants (links) are offered for sharing, but I am not sure which variant is really the right one for the different calendar apps. I think Thunderbird and Apple Calendar are fine with the .ics format. But Outlook and Co?

(b) List view/table: I used to derive the list view automatically from a YAML file. Unfortunately, this was always only semi-fitting (I have several courses, and this table is slightly different everywhere - so one size fits no one ;). So this year I went back to using a manually written table. From experience, I don't think that this manual table provides a good basis for a tool-based export of a calendar ... But, hey, you guys are doing compiler construction. So that would be a nice little exercise :)

(c) Why are we having this conversation in English? 🤣

**Comment by cagix** [comment]
> Ich fürchte auch, dass besser die Daten des Kalenders führend sind und man daraus die Tabelle generieren könnte. Nicht in Google vorgesehene Spalten kann man ja vielleicht dynamisch in einem json/xml/config Format in den Temin-Notizen definieren, so könnten auch diese in der Tabelle auftauchen. Alles erstmal nur als Brainstorming, mal schauen.

Ja, das wäre ein Weg, also Google Calendar -> Markdown Table. Wäre vermutlich relativ einfach - man müsste den .ics-Link verstehen und übersetzen.

Ein anderer wie früher über ein .yaml (die alte Datei habe ich mit d68762f8d3cd8f7cde53b84d6124a6e9218d54b1 entfernt, aber davor ist sie noch "da": [data/schedule.yaml](https://github.com/Compiler-CampusMinden/CB-Vorlesung-Master/blob/0bfab27048d99709f3da0e2d7e562c19871f5f93/data/schedule.yaml)), und von dort nach Markdown Table und Google Calendar. Von .yaml nach Table geht so (habe ich als Hugo-Skript gemacht: [schedule.html](https://github.com/cagix/pandoc-lecture/blob/master/hugo/hugo-lecture/layouts/shortcodes/schedule.html)), aber nach .ics könnte interessant werden (API, 2FA, ...).

Prinzipiell fände ich es ganz schön, wenn das Repo alle nötigen Daten enthalten würde und die Markdown-Dateien im Repo auch in der Vorschau lesbar wären. Andererseits arbeite ich (wenn Zeit bleibt) gerade an einem Markdown-Export der Sourcen, d.h. dabei könnten dann auch die Abbildungen skaliert werden und die Tabellen gebaut werden etc. ... Und ein schicker Kalender-Link zum Einbinden hat ja auch was :)

**Comment by cagix** [comment]
@Ironeer Ich hab mal einen Kalender eingestellt: Kannst Du bitte mal diesen Link probieren? 

https://calendar.google.com/calendar/ical/02297ee2a58f34113eeb16e51ad329dc2ca11d2649b8f196b2478fa75fd4893a%40group.calendar.google.com/public/basic.ics

**Comment by cagix** [comment]
Wenn das für Outlook und Thunderbird funktionieren würde, dann könnte ich das mit unterm "Fahrplan" verlinken :)

**Comment by Ironeer** [comment]
Das sieht gut aus, hat bei mir in Outlook und Thunderbird funktioniert.

**Comment by cagix** [comment]
> Das sieht gut aus, hat bei mir in Outlook und Thunderbird funktioniert.

cool, dann baue ich das morgen in das skript ein :) ... muss dann nur echt aufpassen, dass da die termine immer alle stimmen 🙈

**Comment by cagix** [comment]
dann wäre das zumindest erstmal ein status quo, bis eine generator-lösung existiert.
